M48
; DRILL file {KiCad 7.0.5-0} date 2024 January 10, Wednesday 22:08:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-10T22:08:38+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X106.54Y-98.71
X106.54Y-130.46
X126.86Y-98.71
X126.86Y-130.46
T0
M30
